# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.IntegerField(default=None, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('equipped_background1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Background')),
                ('equipped_button', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.ClickButtonSkin')),
                ('equipped_mltplr', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.ClickMultiplier')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': "Players' stats",
            },
        ),
    ]
