# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinventory',
            old_name='equipped_background1',
            new_name='equipped_background',
        ),
    ]
